name: Model CI/CD with BERT and IMDB Dataset

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Check permissions for model directory
      run: |
        mkdir -p model-test
        ls -ld model-test

    - name: Train model
      run: python model.py

    - name: Debug directory
      run: ls -R

    - name: Upload Model
      uses: actions/upload-artifact@v3
      with:
        name: model-artifact
        path: model-test/

    - name: Run tests
      run: pytest test_model.py
