name: Model CI/CD with BERT and IMDB Dataset

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Train model
      run: python model.py
      
    - name: Add model files to git
      run: |
        git config --local user.email "reemsameh522@gmail.com"
        git config --local user.name "reemSameh21"
        git add model-test/
        git commit -m "Add trained model files" || echo "No changes to commit"

    - name: Push changes
      run: |
        git push https://${{ secrets.GITHUB_TOKEN }}:x-oauth-basic@github.com/reemSameh21/imdb-sentiment-analysis-with-bert.git HEAD:main

    - name: Run tests
      run: pytest test_model.py
